TOPIC: SHAPE and RESHAPE
Task
You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.


Input Format
A single line of input containing  space separated integers.

Output Format
Print the X NumPy array.


Sample Input
1 2 3 4 5 6 7 8 9

Sample Output
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [1]:
import numpy as np
a = list(map(int, input().split()))
print(np.array(a).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


TOPIC: ARRAY
Task

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

Input Format
A single line of input containing space separated numbers.

Output Format
Print the reverse NumPy array with type float.

Sample Input
1 2 3 4 -8 -10

Sample Output
[-10.  -8.   4.   3.   2.   1.]

In [2]:
import numpy as np
a = np.array(input().split(), float)
print(a[::-1])

[9. 8. 7. 6. 5. 4. 3. 2. 1.]


TOPIC: TRANSPOSE and FLATTEN
Task
You are given a X integer array matrix with space separated elements ( = rows and  = columns).
Your task is to print the transpose and flatten results.

Input Format
The first line contains the space separated values of  and .
The next  lines contains the space separated elements of  columns.

Output Format
First, print the transpose array and then print the flatten.


Sample Input
2 2
1 2
3 4

Sample Output
[[1 3]
 [2 4]]
[1 2 3 4]

In [6]:
import numpy as np
row, column = map(int, input().split())
arr = np.array([input().split() for _ in range(row)], int)
print(np.transpose(arr))
print(arr.flatten())

[[2]
 [3]]
[2 3]


TOPIC: MAX and MIN
Task
You are given a 2-D array with dimensions N x M.
Your task is to perform the min function over axis 1 and then find the max of that.

Input Format
The first line of input contains the space separated values of N and M.
The next N lines contains M space separated integers.

Output Format
Compute the min along axis 1 and then print the max of that result.

Sample Input
4 2
2 5
3 7
1 3
4 0

Sample Output
3

In [7]:
import numpy as np
n, m = map(int, input().split())
a = np.array([input().split() for _ in range(n)], int)
print(np.max(np.min(a, axis=1)))

7


TOPIC: CONCATENATE
Task
You are given two integer arrays of size N x P and M x P (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

Input Format
The first line contains space separated integers N,M and P.
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the P columns.

Output Format
Print the concatenated array of size (N + M) x P.


Sample Input
4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 

Sample Output
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

In [ ]:
import numpy as np
n,m,p = map(int,input().split())
arr1 = np.array([input().split() for _ in range(n)],int)
arr2 = np.array([input().split() for _ in range(m)],int)
print(np.concatenate((arr1, arr2), axis = 0))

TOPIC: Eye and Identity
Task
Your task is to print an array of size N x M with its main diagonal elements as 1's and 0's everywhere else.

Note
In order to get alignment correct, please insert the line numpy.set_printoptions(legacy='1.13') below the numpy import.

Input Format
A single line containing the space separated values of N and M.
N denotes the rows.
M denotes the columns.

Output Format
Print the desired N x M array.

Sample Input
3 3

Sample Output
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

In [8]:
import numpy as np
np.set_printoptions(legacy='1.13')
n,m = map(int, input().split())
print(np.eye(n,m))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


TOPIC: Floor, Ceil and Rint
Task
You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

Note
In order to get the correct output format, add the line numpy.set_printoptions(legacy='1.13') below the numpy import.

Input Format
A single line of input containing the space separated elements of array A.

Output Format
On the first line, print the floor of A.
On the second line, print the ceil of A.
On the third line, print the rint of A.

Sample Input
1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

Sample Output
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

In [ ]:
import numpy as np
np.set_printoptions(legacy='1.13')
arr = np.array(list(map(float, input().split())))
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

TOPIC: Sum and Prod
Task
You are given a 2-D array with dimensions N x M.
Your task is to perform the sum tool over axis 0 and then find the product of that result.

Input Format
The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.

Output Format
Compute the sum along axis 0. Then, print the product of that sum.

Sample Input
2 2
1 2
3 4

Sample Output
24

In [ ]:
import numpy as np
N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)], int)
print(np.prod(np.sum(A, axis=0)))

TOPIC: Zeros and Ones
Task
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format
A single line containing the space-separated integers.

Constraints
1 < each integer < 3

Output Format
First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

Sample Input 
3 3 3

Sample Output 
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]

Explanation 
Print the array built using numpy.zeros and numpy.ones tools and you get the result as shown.

In [10]:
import numpy as np
shape = list(map(int, input().split()))
print(np.zeros(shape, dtype = int))
print(np.ones(shape, dtype = int))

[[[[[[[[[0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        ..., 
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]]

       [[0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        ..., 
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]]

       [[0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        ..., 
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]]

       ..., 
       [[0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        ..., 
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]]

       [[0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        ..., 
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]]

       [[0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        [0 0 0 ..., 0 0 0]
        ..., 
  

TOPIC: Array Mathematics
Task
You are given two integer arrays, A and B of dimensions N x M.
Your task is to perform the following operations:
Add (A + B)
Subtract (A - B)
Multiply (A * B)
Integer Division (A / B)
Mod (A % B)
Power (A ** B)

Note
There is a method numpy.floor_divide() that works like numpy.divide() except it performs a floor division.

Input Format
The first line contains two space separated integers, N and M.
The next N lines contains M space separated integers of array A.
The following N lines contains M space separated integers of array B.

Output Format
Print the result of each operation in the given order under Task.

Sample Input
1 4
1 2 3 4
5 6 7 8

Sample Output
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]] 

Use // for division in Python 3.

In [ ]:
import numpy as np
n, m = map(int, input().split())
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)
print(a + b)
print(a - b)
print(a * b)
print(a // b)
print(a % b)
print(a ** b)