In [2]:
import numpy as np

>>np.array(object, dtype = None, ndmin = 0)
object: Any object exposing the array interface method returns an array, or any (nested) sequence
dtype: Desired data type of array, optional
ndmin: Specifies minimum dimensions of resultant array

Example 1
import numpy as np
a = np.array([1,2,3])
print(a)
The output is as follows −
[1 2 3]

Example 2
# more than one dimensions
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)
The output is as follows −
[[1 2]
[3 4]]

Example 3
# minimum dimensions
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)
The output is as follows −
[[1 2 3 4 5]]

Example 4
# dtype parameter
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print (a)
The output is as follows −
[ 1.+0.j 2.+0.j 3.+0.j]

In [1]:
#EXAMPLE-1
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#EXAMPLE-2
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
#EXAMPLE-3
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [4]:
#EXAMPLE-4
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# Task 1
You are given a space separated list of numbers.
Your task is to print a reversed Numpy array with the element type float.

Input Format
A single line of input containing space separated numbers.
Output Format
Print the reverse NumPy array with type float.

Sample Input
1 2 3 4 -8 -10
Sample Output
[-10. -8. 4. 3. 2. 1.]


In [5]:
ls = list(map(int, input().split()))
arr = np.array(ls)
flp = np.flip(arr)
print(np.array(flp, dtype = 'float'))

[5. 4. 3. 2. 1.]


# Task 2
You are given a space separated list of nine integers. Your task is to convert this list into 3x3 numpy array.

Input Format
A single line of input containing space separated integers.
Output Format
Print the 3x3 numpy array.

Sample Input
1 2 3 4 5 6 7 8 9
Sample Output
[[1 2 3]
[4 5 6]
[7 8 9]]

In [3]:
print(np.array(list(map(int, input().split()))).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
