>>np.array(object, dtype = None, ndmin = 0)
object: Any object exposing the array interface method returns an array, or any (nested) sequence
dtype: Desired data type of array, optional
ndmin: Specifies minimum dimensions of resultant array

Example 1
import numpy as np
a = np.array([1,2,3])
print(a)
The output is as follows −
[1 2 3]

Example 2
# more than one dimensions
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)
The output is as follows −
[[1 2]
[3 4]]

Example 3
# minimum dimensions
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)
The output is as follows −
[[1 2 3 4 5]]

Example 4
# dtype parameter
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print (a)
The output is as follows −
[ 1.+0.j 2.+0.j 3.+0.j]

In [1]:
#EXAMPLE-1
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#EXAMPLE-2
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
#EXAMPLE-3
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [4]:
#EXAMPLE-4
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
