In [2]:
import numpy as np

>>np.array(object, dtype = None, ndmin = 0)
object: Any object exposing the array interface method returns an array, or any (nested) sequence
dtype: Desired data type of array, optional
ndmin: Specifies minimum dimensions of resultant array

Example 1
import numpy as np
a = np.array([1,2,3])
print(a)
The output is as follows −
[1 2 3]

Example 2
# more than one dimensions
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)
The output is as follows −
[[1 2]
[3 4]]

Example 3
# minimum dimensions
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)
The output is as follows −
[[1 2 3 4 5]]

Example 4
# dtype parameter
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print (a)
The output is as follows −
[ 1.+0.j 2.+0.j 3.+0.j]

In [1]:
#EXAMPLE-1
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#EXAMPLE-2
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
#EXAMPLE-3
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [4]:
#EXAMPLE-4
import numpy as np
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# Task 1
You are given a space separated list of numbers.
Your task is to print a reversed Numpy array with the element type float.

Input Format
A single line of input containing space separated numbers.
Output Format
Print the reverse NumPy array with type float.

Sample Input
1 2 3 4 -8 -10
Sample Output
[-10. -8. 4. 3. 2. 1.]


In [5]:
ls = list(map(int, input().split()))
arr = np.array(ls)
flp = np.flip(arr)
print(np.array(flp, dtype = 'float'))

[5. 4. 3. 2. 1.]


# Task 2
You are given a space separated list of nine integers. Your task is to convert this list into 3x3 numpy array.

Input Format
A single line of input containing space separated integers.
Output Format
Print the 3x3 numpy array.

Sample Input
1 2 3 4 5 6 7 8 9
Sample Output
[[1 2 3]
[4 5 6]
[7 8 9]]

In [3]:
print(np.array(list(map(int, input().split()))).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Mathematical Functions import numpy as np a = np.array([0,30,45,60,90])
print ('Sine of different angles:' )
# Convert to radians by multiplying with pi/180
1. print(np.sin(a*np.pi/180)) 
print ('Cosine values for angles in array:') 
2. print (np.cos(a*np.pi/180) )
print ('Tangent values for given angles:') 
3. print (np.tan(a*np.pi/180))
print('value of pi') print(np.pi)

# Functions for Rounding 
1. numpy.around()
This is a function that returns the value rounded to the desired precision. The function takes the following parameters. 
2. numpy.around(a,decimals)
The number of decimals to round to. Default is 0. If negative, the integer is rounded to position to the left of the decimal point


In [4]:
a = np.array([0,30,45,60,90])
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [5]:
import numpy as np 
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
print ('Original array:') 
print (a) 
print ('After rounding:') 
print (np.around(a))
print (np.around(a, decimals = 1))

Original array:
[  1.      5.55  123.      0.567  25.532]
After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]


In [9]:
arr = np.array({'a':10, 'b': 20}, dtype = 'object')
print(arr)
print(arr.dtype)
print(type(arr))

{'a': 10, 'b': 20}
object
<class 'numpy.ndarray'>


In [13]:
#IMPORTANT FUNCTIONS
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#Sum of all elements
out1 = np.sum(arr,axis=0) # 0 = along with row (vertical way)
out2 = np.sum(arr,axis=1) # 1 = along with column (horizontal way)

print("Column Wise Addition: ", out1)
print("Row Wise Addition: ", out2)

Column Wise Addition:  [15 18 21 24]
Row Wise Addition:  [10 26 42]


In [26]:
#Round Off
a = 3.54575 #It gives priority to the nearest even number
out1 = np.round(a,0)
out2 = np.round(a,2)
out3 = np.round(a,3)
out4 = np.round(a,4)
out5 = np.round(a,5)
print(out1)
print(out2)
print(out3)
print(out4)

4.0
3.55
3.546
3.5458


In [28]:
#Ceil Function
a = np.array([-3.5, 2.23, 1.009])

out = np.floor(a)
b = np.ceil(a)
print(b)
print(out)

[-3.  3.  2.]
[-4.  2.  1.]


In [44]:
#Zeros, Ones, Empty, Eye, Full
print("Zeros: ",np.zeros((2,2)))
print("Ones: ",np.ones((2,4)))
print("Empty(Random values): ",np.empty((2,2)))
print("Identity Matrix: ", np.eye(2))
print("Full: ",np.full((2,2),7))

Zeros:  [[0. 0.]
 [0. 0.]]
Ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Empty(Random values):  [[0. 0.]
 [0. 0.]]
Identity Matrix:  [[1. 0.]
 [0. 1.]]
Full:  [[7 7]
 [7 7]]


In [18]:
a = np.array([-2.7, 1.3, 3.5, 3.9])
b = np.around(a,0)
print(b)

[-3.  1.  4.  4.]
